import { defineTable } from "convex/server";
import { v } from "convex/values";

export const taskState = v.union(
  v.literal("queued"),
  v.literal("running"),
  v.literal("awaiting_approval"),
  v.literal("succeeded"),
  v.literal("failed"),
  v.literal("canceled"),
  v.literal("timed_out"),
  v.literal("needs_reconciliation"),
);
export const contextRef = v.object({
  entityId: v.id("entities"),
  revision: v.number(),
});
export const delivery = v.object({ to: v.string(), subject: v.string() });
const owned = { workspaceId: v.id("workspaces"), ownerId: v.id("users") };
export const executionTables = {
  taskRuns: defineTable({
    ...owned,
    prompt: v.string(),
    model: v.string(),
    contextRefs: v.optional(v.array(contextRef)),
    state: taskState,
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
    deadlineAt: v.number(),
    workflowId: v.optional(v.string()),
    journalCleanedAt: v.optional(v.number()),
    contentClearedAt: v.optional(v.number()),
    retentionCheckedAt: v.optional(v.number()),
    reservationId: v.optional(v.id("executionReservations")),
    modelDispatch: v.union(
      v.literal("not_started"),
      v.literal("started"),
      v.literal("settled"),
    ),
    modelDispatchedAt: v.optional(v.number()),
    result: v.optional(v.string()),
    detail: v.optional(v.string()),
    delivery: v.optional(delivery),
    intentId: v.optional(v.id("externalActionIntents")),
    stopReason: v.optional(
      v.union(v.literal("canceled"), v.literal("timed_out")),
    ),
    providerRequestId: v.optional(v.string()),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    costMicros: v.optional(v.number()),
    recoveryCount: v.number(),
    routineId: v.optional(v.id("executionRoutines")),
  })
    .index("by_owner", ["workspaceId", "ownerId", "createdAt"])
    .index("by_owner_active", ["workspaceId", "ownerId", "active"])
    .index("by_workspace_active", ["workspaceId", "active"]),
  executionPolicies: defineTable({
    workspaceId: v.id("workspaces"),
    allowedModelIds: v.array(v.string()),
    monthlyWorkspaceMicros: v.number(),
    monthlyUserMicros: v.number(),
    allowEmail: v.boolean(),
    updatedAt: v.number(),
  }).index("by_workspace", ["workspaceId"]),
  executionBudgets: defineTable({
    workspaceId: v.id("workspaces"),
    scope: v.string(),
    period: v.string(),
    reservedMicros: v.number(),
    spentMicros: v.number(),
  }).index("by_scope", ["workspaceId", "scope", "period"]),
  executionReservations: defineTable({
    ...owned,
    taskId: v.id("taskRuns"),
    period: v.string(),
    reservedMicros: v.number(),
    settledMicros: v.optional(v.number()),
    state: v.union(
      v.literal("reserved"),
      v.literal("settled"),
      v.literal("released"),
      v.literal("uncertain"),
    ),
    createdAt: v.number(),
    settledAt: v.optional(v.number()),
  }).index("by_task", ["taskId"]),
  executionApprovals: defineTable({
    ...owned,
    taskId: v.id("taskRuns"),
    intentId: v.id("externalActionIntents"),
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected"),
      v.literal("expired"),
      v.literal("canceled"),
    ),
    expiresAt: v.number(),
    createdAt: v.number(),
    decidedAt: v.optional(v.number()),
  }).index("by_task", ["taskId"]),
  externalActionIntents: defineTable({
    ...owned,
    taskId: v.id("taskRuns"),
    kind: v.literal("email"),
    provider: v.literal("resend"),
    to: v.string(),
    subject: v.string(),
    text: v.string(),
    contextRefs: v.optional(v.array(contextRef)),
    status: v.union(
      v.literal("prepared"),
      v.literal("approved"),
      v.literal("dispatching"),
      v.literal("submitted"),
      v.literal("failed"),
      v.literal("uncertain"),
      v.literal("canceled"),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
    dispatchedAt: v.optional(v.number()),
    providerId: v.optional(v.string()),
    detail: v.optional(v.string()),
  })
    .index("by_task", ["taskId"])
    .index("by_provider", ["provider", "providerId"]),
  executionEvents: defineTable({
    ...owned,
    taskId: v.id("taskRuns"),
    type: v.string(),
    createdAt: v.number(),
    actorId: v.optional(v.id("users")),
    detail: v.optional(v.string()),
  }).index("by_task", ["taskId", "createdAt"]),
  executionRoutines: defineTable({
    ...owned,
    name: v.string(),
    prompt: v.string(),
    model: v.string(),
    intervalMinutes: v.optional(v.number()),
    eventKey: v.optional(v.string()),
    enabled: v.boolean(),
    revision: v.number(),
    nextRunAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
    lastTaskId: v.optional(v.id("taskRuns")),
    lastStatus: v.optional(v.string()),
  }).index("by_owner", ["workspaceId", "ownerId"]),
  executionTriggers: defineTable({
    routineId: v.id("executionRoutines"),
    key: v.string(),
    taskId: v.id("taskRuns"),
    createdAt: v.number(),
  }).index("by_key", ["routineId", "key"]),
};
